LineLength:
  Max: 250
SingleSpaceBeforeFirstArg:
  Enabled: false
SpaceBeforeFirstArg:
  Enabled: false
AbcSize:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
PerceivedComplexity:
  Enabled: false
MethodLength:
  Enabled: false
Style/FileName:
  Enabled: false
